blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/blak0p/splice/discussions
    about: Please use Discussions for questions, ideas, or general help
